### ISSUE TITLE
Terminal Error during config setup

### ISSUE THREAD

**Issue by BTClown** [Exohayvan/Crypto-Seed-Project#2]
**Describe the bug**
when i enter the btc address the terminal kicks me out and shuts down

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 0.0.3-alpha

**Additional context**

**Comment by Exohayvan** [comment]
Closing. No response, unable to reproduce on 5 different machines. If still having issue reply and we can reopen

**Comment by BTClown** [comment]
> Closing. No response, unable to reproduce on 5 different machines. If still having issue reply and we can reopen

yeah so its on the windows version and its v0.0.3-alpha

**Comment by Exohayvan** [comment]
> yeah so its on the windows version and its v0.0.3-alpha

What is the address you are putting in. What is your system version?
