### ISSUE TITLE
Windows Build colors don't match Linux Build

### ISSUE THREAD

**Issue by TheRealJedaru** [Exohayvan/Crypto-Seed-Project#3]
**Describe the bug**
Windows build colors don't match Linux build(as title says xd)

**Screenshots**
![image](https://user-images.githubusercontent.com/128835563/228308145-6c56452e-1c78-4ba1-85c9-cfb3fe6347a8.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 0.0.3-alpha

**Comment by Exohayvan** [comment]
Fixed in newest build. Will release when other build compile.
